services:
  frontend-build:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: export
    image: todo-frontend-export:latest
    container_name: todo-frontend
    command: ["/bin/sh", "-c", "cp -r /export/* /output && echo ✅ build copied"]
    volumes:
      - ./frontend/build:/output
    restart: "no"

  backend:
    build:
      context: ./backend
    image: todo-backend:latest
    container_name: todo-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: ./nginx
    image: todo-nginx:latest
    container_name: todo-nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
